user1 = User.create(email: "user@email.com", password: 123123)
# bench = Lift.create(name: "Bench Press", user_id: user1.id)
# squat = Lift.create(name: "Back Squat", user_id: user1.id)
# press = Lift.create(name: "Overhead Press", user_id: user1.id)
# deadlift = Lift.create(name: "Deadlift", user_id: user1.id)
# bench_1 = Workout.create(format: "3x5", projected_1rm: 215, lift_id: bench.id)
# bench_2 = Workout.create(format: "3x3", projected_1rm: 220, lift_id: bench.id)
# bench_2 = Workout.create(format: "5-3-1", projected_1rm: 225, lift_id: bench.id)
# bench_2 = Workout.create(format: "deload", projected_1rm: 170, lift_id: bench.id)
# bench_2 = Workout.create(format: "3x5", projected_1rm: 220, lift_id: bench.id)
#
# deadlift_1 = Workout.create(format: "3x5", projected_1rm: 285, lift_id: deadlift.id)
# deadlift_1 = Workout.create(format: "3x3", projected_1rm: 295, lift_id: deadlift.id)
# deadlift_1 = Workout.create(format: "5-3-1", projected_1rm: 305, lift_id: deadlift.id)
#
# press_1 = Workout.create(format: "3x5", projected_1rm: 125, lift_id: press.id)
# press_1 = Workout.create(format: "3x3", projected_1rm: 130, lift_id: press.id)
# press_1 = Workout.create(format: "5-3-1", projected_1rm: 135, lift_id: press.id)
# press_1 = Workout.create(format: "Deload", projected_1rm: 95, lift_id: press.id)
# press_1 = Workout.create(format: "3x5", projected_1rm: 130, lift_id: press.id)
#
# squat_1 = Workout.create(format: "3x5", projected_1rm: 245, lift_id: squat.id)
# squat_2 = Workout.create(format: "3x3", projected_1rm: 255, lift_id: squat.id)
# squat_3 = Workout.create(format: "5-3-1", projected_1rm: 275, lift_id: squat.id)
# squat_4 = Workout.create(format: "Deload", projected_1rm: 185, lift_id: squat.id)
# squat_5 = Workout.create(format: "3x5", projected_1rm: 255, lift_id: squat.id)

# sett1 = Sett.create(reps: 5, weight: 155, projected_1rm: 225, workout_id: workout1.id)
# sett2 = Sett.create(reps: 5, weight: 175, projected_1rm: 225, workout_id: workout1.id)
# sett3 = Sett.create(reps: 7, weight: 185, projected_1rm: 225, workout_id: workout1.id)
